expr -> expr_tier1

expr_tier1 -> expr_tier2 | expr_tier2 if expr_tier1 else expr_tier1
expr_tier2 -> expr_tier3 | expr_tier2 or expr_tier3
expr_tier3 -> expr_tier4 | expr_tier3 and expr_tier4
expr_tier4 -> expr_tier5 | not expr_tier4
expr_tier5 -> expr_tire6 | expr_tier5 relation_operator expr_tier6
expr_tier6 -> expr_tire7 | expr_tier7 additive_operator expr_tier6
expr_tier7 -> expr_tier8 | expr_tier8 multiplicative_operator expr_tier7
expr_tier8 -> expr_tier9 | '-' expr_tier8
expr_tier9 -> expr_tier10 | expr_tier9 '.' ID | expr_tier9 '[' ID ']'
expr_tier10 -> '(' expr_tier1 ')' | literal

relation_operator -> "==" | "!=" | "<" | ">" | "<=" | ">=" | is
additive_operator -> "+" | "-"
multiplicative_operator -> "*" | "//" | "%"

literal -> ID
ID -> 'x'
