expr -> tier1

tier1 -> tier2 | tier2 i tier1 e tier1
tier2 -> tier3 | tier2 o tier3
tier3 -> tier4 | tier3 a tier4
tier4 -> tier5 | n tier4
tier5 -> tier6 | tier5 relation_operator tier6
tier6 -> tier7 | tier7 additive_operator tier6
tier7 -> tier8 | tier8 multiplicative_operator tier7
tier8 -> tier9 | "-" tier8
tier9 -> tier10 | tier9 "." ID | tier9 "[" ID "]"
tier10 -> "(" tier1 ")" | literal

relation_operator -> "=" | "<" | ">"
additive_operator -> "+" | "-"
multiplicative_operator -> "*" | "//" | "%"

literal -> ID
ID -> "x"
